local Package = game:GetService("ReplicatedStorage").Fusion
local springCoefficients = require(Package.Motion.springCoefficients)

return function()
	it("should return the identity matrix for zero time", function()
		local posPos, posVel, velPos, velVel = springCoefficients(0, 5.1, 3.4)

		expect(posPos).to.equal(1)
		expect(posVel).to.equal(0)
		expect(velPos).to.equal(0)
		expect(velVel).to.equal(1)
	end)

	it("should return the identity matrix for zero speed", function()
		local posPos, posVel, velPos, velVel = springCoefficients(5.1, 3.4, 0)

		expect(posPos).to.equal(1)
		expect(posVel).to.equal(0)
		expect(velPos).to.equal(0)
		expect(velVel).to.equal(1)
	end)

	-- FUTURE: these tests use numbers generated by the code, which may include
	-- some numerical imprecision. For best results, these numbers should
	-- eventually be replaced by results from a proper mathematical program with
	-- infinite precision.

	local ERROR_MARGIN = 0.00001

	it("should return reasonable underdamped values", function()
		local posPos, posVel, velPos, velVel = springCoefficients(3.6, 0.2, 6.3)

		expect(posPos).to.be.near(-0.010751908521633928, ERROR_MARGIN)
		expect(posVel).to.be.near(-0.0006530742047237514, ERROR_MARGIN)
		expect(velPos).to.be.near(0.025920515185485687, ERROR_MARGIN)
		expect(velVel).to.be.near(-0.009106161525730076, ERROR_MARGIN)
	end)

	it("should return reasonable critically damped values", function()
		local posPos, posVel, velPos, velVel = springCoefficients(0.24, 1, 3.6)

		expect(posPos).to.be.near(0.7856253267423104, ERROR_MARGIN)
		expect(posVel).to.be.near(0.10115347554622023, ERROR_MARGIN)
		expect(velPos).to.be.near(-1.310949043079014, ERROR_MARGIN)
		expect(velVel).to.be.near(0.057320302809524805, ERROR_MARGIN)
	end)

	it("should return reasonable overdamped values", function()
		local posPos, posVel, velPos, velVel = springCoefficients(1.74, 8.4, 7.2)

		expect(posPos).to.be.near(0.4748290157123269, ERROR_MARGIN)
		expect(posVel).to.be.near(0.003939512259321826, ERROR_MARGIN)
		expect(velPos).to.be.near(-0.2042243155232435, ERROR_MARGIN)
		expect(velVel).to.be.near(-0.0016943871752413216, ERROR_MARGIN)
	end)
end